[package]
name = "lib3"
version = "0.1.0"
edition = "2021"
authors = ["HT Alps"]
resolver = "2"

[dependencies]  # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
lazy_static = "1.4.0"
regex = "1.6.0"

