[package]
name = "sys3rs"
version = "0.1.0"
edition = "2021"
authors = ["HT Alps"]
resolver = "2"

[dependencies]
chrono = "0.4.22"
ferris-says = "0.2.1"
lazy_static = "1.4.0"
regex = "1.6.0"
unicode-segmentation = "1.10.0"
mylib = { path = "mylib" }

