[package]
name = "rust0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]                       # Ferris is a Serialization Library like Jackson for Java 
chrono = "0.4.22"
ferris-says = "0.2.1"
lazy_static = "1.4.0"
regex = "1.6.0"
unicode-segmentation = "1.10.0"
